### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by EliasDeuss** [tastelessjolt/flutter_dynamic_icon#1]
Will android support come to this package?

**Comment by tastelessjolt** [comment]
Nope, since Android doesn't have an API to dynamically change App icon, it won't be coming to this package unless Android adds it later, then you can reopen and I might implement it. But right now, there's no way of doing this on Android for all launchers.

**Comment by chentianxin** [comment]
Maybe <activity-alias> this can realize the Android dynamic switch icon and name function
https://developer.android.com/guide/topics/manifest/activity-alias-element
https://blog.csdn.net/fu908323236/article/details/78813136
Can you give it a try thanks
