### ISSUE TITLE
How to add icons for iPad (152x152, 167x167)?

### ISSUE THREAD

**Issue by nohli** [tastelessjolt/flutter_dynamic_icon#14]
**Describe the bug**

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, (...). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90892: Missing recommended icon - The bundle does not contain an alternate app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons
> 
> ITMS-90892: Missing recommended icon - The bundle does not contain an alternate app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 10.0. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

It worked fine without this warning before June 11th.

So far, I've tried to add the requested icon sizes under `CFBundleIcons~ipad` and name them differently, but didn't work.

On this day, also the following warning appeared:

> ITMS-90890: Missing recommended icon - The bundle does not contain an alternate app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons

It was because I only had one 160x160 `picture.png` and got fixed by renaming it to `picture@3x.png` and adding `picture@2x.png` with 120x120 resolution.

**Comment by nohli** [comment]
This fixes the 152x152 icon file:
https://stackoverflow.com/questions/36436031/missing-required-icon-file-the-bundle-does-not-contain-an-app-icon-for-ipad-of

Still struggling with 167x167.

**Comment by ro1pixel** [comment]
@nohli did you manage to solve this? I'm referring to the stackoverflow but cannot get this to work.. :( any chance you can provide the steps you took?

thanks!

**Comment by nohli** [comment]
Oh, don't remember, but it was some answer before June 2021.

Try an app icon creator like [Assets Maker](https://apps.apple.com/de/app/assets-maker-for-xcode/id1561328879).
