### ISSUE TITLE
iOS 15 displays successful but does not change

### ISSUE THREAD

**Issue by armandojimenez** [tastelessjolt/flutter_dynamic_icon#16]
**Describe the bug**
A Dialog display saying the change was successful, but the icon change to an empty placeholder one

**To Reproduce**
on iOS 15, configure the project using following the project instructions

**Expected behavior**

Error:
```
[default] +[LSApplicationProxy applicationProxyFor*] is not a supported method for getting the LSApplicationProxy for the current process, use +[LSBundleProxy bundleProxyForCurrentProcess] instead.
[default] LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
[default] Attempt to map database failed: permission was denied. This attempt will not be retried.
[db] Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=264, _LSFunction=-[_LSDReadClient getServerStoreWithCompletionHandler:]}
flutter: App icon change successful
```

**Comment by tastelessjolt** [comment]
I just saw these issues. 
Is the issue resolved? And why was the issue closed? 
If it was fixed, please post the solution it is alright with you.

**Comment by armandojimenez** [comment]
Hi, Its weird and I think is my device or a weird caching issue. For some of the images, it shows as an empty icon and I need to restart the device to see it, and it happens with the same 2 icons, but does not happen in the simulator or in my ipads, so I don't know :(

![IMG_6847](https://user-images.githubusercontent.com/28992210/146701822-f6027bd4-6eaf-4013-aa07-27726d8e0f1c.PNG)

**Comment by tastelessjolt** [comment]
Then, it might probably be a bug on the iOS side of things. 
It seems like there are similar issues https://developer.apple.com/forums/thread/682648

**Comment by armandojimenez** [comment]
Thanks! Another question since you are here, If my app also works with iPads, do I need different icons resolutions? or the 120 x 120 and 180 x 180 will do?

**Comment by tastelessjolt** [comment]
> Thanks! Another question since you are here, If my app also works with iPads, do I need different icons resolutions? or the 120 x 120 and 180 x 180 will do?

It will work but it is better to conform to the _iOS Human Interface Guidelines_
You can see more details here: 
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/#:~:text=no%20rounded%20corners-,App%20Icon%20Sizes,-Every%20app%20must
