### ISSUE TITLE
badge support not working on android

### ISSUE THREAD

**Issue by CharlyKeleb** [tastelessjolt/flutter_dynamic_icon#26]
**Describe the bug**

**To Reproduce**

FlutterDynamicIcon.setApplicationIconBadgeNumber(5);

**Expected behavior**
This should update the badger on both platforms( IOS and Android), it turns out that it only works on android

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A03]
 - OS: [e.g. Android]
 - Version [e.g. 10]

*

**Comment by tastelessjolt** [comment]
Unfortunately, as far as I know, Android itself doesn't have icon badge numbers. 
Closing the issue.
