### ISSUE TITLE
ITMS-90032: Invalid Image Path - - No image found at the path referenced under key 'CFBundleAlternateIcons': 'image1'

### ISSUE THREAD

**Issue by mobashir0155** [tastelessjolt/flutter_dynamic_icon#6]
Whenever i upload build on app store it succeeds but after some time it gets rejected with the error message as in the tiltle.
Here is my info.plist
`<key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>image1</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>image1</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
		</dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>default</string>
			</array>
			<key>UIPrerenderedIcon</key>
			<false/>
		</dict>
	</dict>`
and icons are placed int flutter->IOS->Runner->APP ICONS with name:
image1@2x.png
image1@3x.png
default@2x.png
default@3x.png
can someone guid me or is there  something i'm missing.

**Comment by hmmdeif** [comment]
@mobashir0155 no idea if you fixed it yourself or not but you need to add the files to your Xcode project at the root level (i.e. don't add them at `Runner/Runner/App Icons`, add them at `Runner`.

**Comment by tastelessjolt** [comment]
I assume this is fixed and closing this issue.

**Comment by nohli** [comment]
Just in case that anyone encounters the same issue:

When copying to Xcode, you can select 'create folder references' or 'create groups'...select groups and it works.
