### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by chentianxin** [tastelessjolt/flutter_dynamic_icon#9]
Maybe this can realize the Android dynamic switch icon and name function

https://developer.android.com/guide/topics/manifest/activity-alias-element

https://blog.csdn.net/fu908323236/article/details/78813136

Can you give it a try thanks

**Comment by tastelessjolt** [comment]
Oh, from just skimming through, it looks like it works. 
Need to check it out in little more detail in how it affects other things.

Thanks for your interest. Will check it out this weekend.

**Comment by chentianxin** [comment]
Hello there.  How is the progress of adapting to Android, because I can't wait to use it.  Thanks 😜

**Comment by GioPan04** [comment]
Hi @tastelessjolt ,
I made a similar plugin ([flutter_icon_switcher](https://github.com/GioPan04/flutter_icon_switcher)) but is only for Android. Maybe tomorrow I could make a pull for this repo with the code of mine. So there will be only one repo, what do you think?

**Comment by tastelessjolt** [comment]
Oh, great. I'd appreciate it. Please make a PR. I think you can stick to the same API as the iOS one for the icon changing. :+1:

**Comment by GioPan04** [comment]
@tastelessjolt Could you please merge my pull? Thanks

**Comment by tastelessjolt** [comment]
> @tastelessjolt Could you please merge my pull? Thanks

Can you check my comments?

**Comment by GioPan04** [comment]
> > @tastelessjolt Could you please merge my pull? Thanks
> 
> Can you check my comments?

Where you commented? I don't see any of your comments and I didn't recive any notification...

**Comment by tastelessjolt** [comment]
> > > @tastelessjolt Could you please merge my pull? Thanks
> > 
> > Can you check my comments?
> 
> Where you commented? I don't see any of your comments and I didn't recive any notification...

Oh, I'm sorry looks like I haven't submitted the comments that I wrote

**Comment by Lcadiou** [comment]
Hello guys,

Can we have any news on this topic please ?
I'd like to use this package for a project, and I'm wondering if iOS will be supported soon :)

Thank you

**Comment by andronasef** [comment]
+1 waiting for this awesome project

**Comment by InfinityCoder88** [comment]
Any news, about merging for both platforms? Thx

**Comment by joknjokn** [comment]
We're also very interested in this! An ETA would be amazing.

**Comment by tastelessjolt** [comment]
Sorry for the long absence
The status right now is that I have made more changes to this PR and have it ready. 
But currently wherever the app icon is changed in Android, the app is closed by the system and doesn't re-open.
If anyone has an idea how to make it work without the app getting closed please share some examples on how it is done.

**Comment by vlkigdm** [comment]
I've edited that PR to my needs and there is no restarts when changing the icon(s).

I've edited the Manifest like this:

- It contains 3 activities - 1 "activity" with android:name=".MainActivity" and 2 "activity-aliases" with android:name=".NoPromoIcons" and android:name=".PromoIcons"
- All 3 activities contains identical "meta-data", "intent-filters" and other fields except for android:name, android:icon, android:roundIcon (.MainActivity and .NoPromoIcons has the default app icons). Also .MainActivity doesn't have android:enabled while .NoPromoIcons contains android:enabled="true" and .PromoIcons - android:enabled="false".
- So when I try to change the icons I use `await DynamicIcon.setAlternateIconName('PromoIcons')` or `await DynamicIcon.setAlternateIconName('NoPromoIcons')` and it works just fine (do not try to switch to .MainActivity!).

**Comment by johnnyjong823** [comment]
Hi
Have you considered using this plugin for Android?
My android version uses this plugin ([flutter_live_icon](https://github.com/DevsOnFlutter/flutter_live_icon))
IOS version use your plugin

His Android plugin has been tested and works normally~

BR
Johnny

**Comment by divshekhar** [comment]
Hello @chentianxin,
As mentioned by @johnnyjong823, you can consider ([flutter_live_icon](https://github.com/DevsOnFlutter/flutter_live_icon)) for the android support. Flutter live icon has been fully tested for android and works fine. We can also look forward towards merging the plugin for both Android and iOS support. Would like to hear from you!

Best Regards
Divyanshu Shekhar

**Comment by chentianxin** [comment]
> 你好@chentianxin， 正如@johnnyjong823提到的，您可以考虑（[flutter_live_icon](https://github.com/DevsOnFlutter/flutter_live_icon)）对Android的支持。Flutter Live icon已经过Android的全面测试，工作正常。我们还可以期待合并插件，同时支持Android和iOS。希望收到您的来信！
> 
> 最好的问候 迪维扬舒·谢哈尔

**Comment by chentianxin** [comment]
> > 你好@chentianxin， 正如@johnnyjong823提到的，您可以考虑（[flutter_live_icon](https://github.com/DevsOnFlutter/flutter_live_icon)）对Android的支持。Flutter Live icon已经过Android的全面测试，工作正常。我们还可以期待合并插件，同时支持Android和iOS。希望收到您的来信！
> > 最好的问候 迪维扬舒·谢哈尔

Thanks

**Comment by chentianxin** [comment]
> Hello @chentianxin, As mentioned by @johnnyjong823, you can consider ([flutter_live_icon](https://github.com/DevsOnFlutter/flutter_live_icon)) for the android support. Flutter live icon has been fully tested for android and works fine. We can also look forward towards merging the plugin for both Android and iOS support. Would like to hear from you!
> 
> Best Regards Divyanshu Shekhar

Thanks
